//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleSecurity.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class permission
    {
        [Key]
        [Required]
        public long id_permission { get; set; }

        [Required]
        public long id_user { get; set; }

        [Required]
        public int id_role { get; set; }

        [Required]
        public long id_resource { get; set; }
    
        public virtual resource resource { get; set; }
        public virtual role role { get; set; }
        public virtual user user { get; set; }
    }
}
